### ISSUE TITLE
Firefox Login

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#1]
Bug Name: Keys not working when username or password field is selected.
Bug ID: 01
Area Path: STAR Login
Build Number: 1
Severity: HIGH 
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 03/12/2015
Reason: Defect
Status: Open
Environment: Firefox verison 42.0

Description:
When selecting the username or password field on the STAR Login page, all keys other than letters and numbers are unusable. Works on Chrome and I.E.

Steps To Reproduce:
1) Open STAR login page on Firefox
2) Click username field
3) Try using the tab key.

**Comment by VijayBrar** [comment]
@thaffendenplanit 

FF doesn't allow metacharacters like Chrome and IE do. I've tried a workaround but can only allow backspace and enter. Tab and navigation arrows won't be possible on FF only.

Please retest.
