### ISSUE TITLE
No Nav bar or Burger button on Android (tablet and phone)

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#11]
Bug Name: No Nav bar or Burger button on Android (tablet and phone)
Bug ID: 11
Area Path: STAR Home Screen
Build Number: 1
Severity: HIGH
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Shaun Rattue
Reported On: 11/12/2015
Reason: Defect
Status: Open
Environment: Chrome for Android

Logged in on my phone and tablet, neither displayed the navigation bar or the burger menu to open the navigation bar
![img_0076](https://cloud.githubusercontent.com/assets/15983243/11743754/e9d1f4c6-a001-11e5-86ef-15b8c6d6639e.JPG)

**Comment by VijayBrar** [comment]
@rattulator this should be fixed now

Please retest.
