### ISSUE TITLE
Special characters being accepted

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#15]
Bug Name: Special characters accepted where they shouldn't be
Bug ID: 13
Area Path: STAR Personal Details
Build Number: 1
Severity: Low
Priority: Low
Assigned to: Vijay Brar
Reported By: Mitchell Johnson
Reported On: 11/12/2015
Reason: Defect
Status: Open
Environment: Chrome (desktop)

All non-date fields accept special as well as alphanumeric characters. They should not,

**Comment by VijayBrar** [comment]
@rattulator has this now been accepted by Rachel owing to people have specials in their names etc?

**Comment by rattulator** [comment]
it has
