### ISSUE TITLE
DOB wrong format in IE 11 

### ISSUE THREAD

**Issue by sarangan0072000** [VijayBrar/STAR#16]
Bug Name: DOB wrong format in IE
Bug ID: 15
Area Path: STAR Personal Details
Build Number: 1
Severity: Low
Priority: Low
Assigned to: Vijay Brar
Reported By: Sarangan Jeyapalan
Reported On: 11/12/2015
Reason: Defect
Status: Open
Environment: IE11

Description:
Date of birth format in IE browser is in wrong format YYYY/MM/DD instead of DD/MM/YYYY.

Steps To Reproduce:
1) Open STAR personal details page.
2) Enter date of birth 
3) Click save.
4) Refresh

![image](https://cloud.githubusercontent.com/assets/16132155/11746277/3f618b32-a015-11e5-9160-a87689f2b9c0.png)

Expected result
Date appears as 0000-00-00

Actual result 
Details are saved.

**Comment by VijayBrar** [comment]
@sarangan0072000 this should now be fixed (see #7 ).

Please retest.

**Comment by sarangan0072000** [comment]
Re-tested seems fine now.
