### ISSUE TITLE
Smaller fields on personal details for bigger screens

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#18]
Bug Name: Smaller fields on personal details for bigger screens
Bug ID: 18
Area Path: STAR Personal Details
Build Number: 1
Severity: HIGH
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 14/12/2015
Reason: Defect
Status: Open
Environment: I.E, Firefox, chrome on large screens

Description:
As discussed at product demo on larger screens the fields in personal details fill up the whole page and look odd. Therefore they need to be made smaller on these bigger screens.

**Comment by VijayBrar** [comment]
@thaffendenplanit Rachel agreed to leave this as it was too much messing around to alter the size of every input field.
