### ISSUE TITLE
Comma separating every three integer digits in Mobile Number field, IE

### ISSUE THREAD

**Issue by sarangan0072000** [VijayBrar/STAR#19]
Bug Name: Comma separating every three integer digits in Mobile Number field  IE
Bug ID: 19
Area Path: STAR Personal Details
Build Number: 1
Severity: Medium
Priority: Medium
Assigned to: Vijay Brar
Reported By: Sarangan Jeyapalan
Reported On: 14/12/2015
Reason: Defect
Status: Open
Environment: IE 11

Description:
Comma appears in the mobile number field separating every three integers which is not in the design specification

Steps To Reproduce:
1) Open STAR personal details page.
2) Enter 11 digit mobile number in the ''Mobile Number'' field
3) Click Submit.
4) Refresh

Expected result
Mobile Number appears as xxxxxxxxxxx

Actual result : xx,xxxx,xxxx,xxx

![image](https://cloud.githubusercontent.com/assets/16132155/11785985/1c46a308-a27c-11e5-862b-3c0326a8c757.png)

**Comment by VijayBrar** [comment]
@sarangan0072000 this should be fixed now.

Please retest.
