### ISSUE TITLE
Mandatory capital letter message not disappearing

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#2]
Bug Name: Mandatory capital letter message not disappearing
Bug ID: 01
Area Path: STAR Login
Build Number: 1
Severity: HIGH 
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Shaun Rattue
Reported On: 03/12/2015
Reason: Defect
Status: Open
Environment: Chrome

Description:
Having entered a blank username and password, causing the account details criteria to appear, they all disappear as they are met apart from the 'At least one uppercase' message

Steps To Reproduce:
1) Open STAR login page on Chrome
2) Press Submit
3) Observe all error messages apppear
4) enter user details:
Username - srattue
Password - Reutta
5) Observe all error message disappear apart from 'At least one uppercase'

(see screenshot)
![image](https://cloud.githubusercontent.com/assets/15983243/11560806/fb895904-99ba-11e5-9f06-6426747c0341.png)

**Comment by VijayBrar** [comment]
@rattulator thanks for this one. Struggling to get a handle on the issue and been informed that error messages are too detailed which may promote more successful hackery.

Currently reworking error messages, will pass this back to you when I'm done.

**Comment by VijayBrar** [comment]
@thaffendenplanit @rattulator 
This should be working now. Username and password errors have been changed now to the following:
- The error messages for username and password have been replaced by one generic message: 'Invalid username or password'
- This error should appear if any of the following occur:
  - Empty username or password field
  - No capital letter in password field
  - Less than 6 characters in password field
- The username and password fields should **both** highlight if an incorrect username **or** password has been entered
- The error highlight for either field should disappear as soon as a character has been typed in the relevant field. This is not dependent on correct characters being entered.

**Comment by rattulator** [comment]
Message is appearing when I enter my normal details, is this due to it not being hooked up to the backend or a bug?
![image](https://cloud.githubusercontent.com/assets/15983243/11718507/34af5042-9f4e-11e5-8e35-95cf58ef7096.png)

**Comment by thaffendenplanit** [comment]
It's not hooked up at the moment, I've noticed the error message does not appear from lack of a captial letter, only from less than 6 characters in password field.

**Comment by VijayBrar** [comment]
@rattulator error messages should now be appearing as expected. Front end validation works independently of back end checks. You should get no action and no errors if details are entered correctly.

**Comment by VijayBrar** [comment]
@thaffendenplanit I'm working on the enter bug :)
