### ISSUE TITLE
"</div>" appearing in mobile number field of Travel and Accomdation

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#20]
Bug Name: "</div>" appearing in mobile number field of Travel and Accomdation
Bug ID: 120
Area Path: STAR Travel and Accomodation
Build Number: 1
Severity: HIGH
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Shaun Rattue
Reported On: 15/12/2015
Reason: Defect
Status: Open
Environment: Chrome (desktop/mobile/tablet)

![image](https://cloud.githubusercontent.com/assets/15983243/11807624/cd352fcc-a312-11e5-82ab-66cd81674421.png)

**Comment by VijayBrar** [comment]
@rattulator 

Please retest.
