### ISSUE TITLE
Chrome not automatically filling date with current date

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#21]
Bug Name: Chrome not automatically filling date with current date
Bug ID: 21
Area Path: STAR Travel and accommodation
Build Number: 2
Severity: HIGH
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 15/12/2015
Reason: Defect
Status: Open
Environment:  chrome

Description:
Chrome does not automatically set date to the current date on the travel and accommodation form
![chrome being poor](https://cloud.githubusercontent.com/assets/15983238/11808803/bab76196-a31a-11e5-9463-bec76ffd233e.png)

**Comment by VijayBrar** [comment]
@thaffendenplanit 

Please retest.
