### ISSUE TITLE
Fields on personal details still have asterisk implying they are mandatory

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#22]
Fields on personal details still have asterisk implying they are mandatory
Bug ID: 22
Area Path: STAR Personal details
Build Number: 2
Severity: HIGH
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 15/12/2015
Reason: Defect
Status: Open
Environment: chrome, fire fox, I.E

Description:
After discussion it was decieded none of the fields on personal details need to be mandatory, however many of these fields still have an asterisk by them and warning messages when the form is submitted with the field
![asterisks](https://cloud.githubusercontent.com/assets/15983238/11809808/46c52cf8-a321-11e5-9ef3-1ed993710fca.png)
 empty.

**Comment by VijayBrar** [comment]
@thaffendenplanit 

Please retest
