### ISSUE TITLE
Location Menu not defaulting to Primary Location for selected project

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#25]
Bug ID: 25
Area Path: STAR Project Management
Build Number: 3
Severity: LOW
Priority: LOW
Assigned to: Vijay Brar
Reported By: Shaun Rattue
Reported On: 08/01/16
Reason: Defect
Status: Open
Environment: chrome

When a new project is added, along with a primary location, the location is not selected by default in the Location drop down. This occurs when the Project is newly added or already existing in the dropdown.
![image](https://cloud.githubusercontent.com/assets/15983243/12201850/5fc5e098-b61e-11e5-853b-f852eaa9c52b.png)

**Comment by VijayBrar** [comment]
@rattulator 

Fixed - this should now work fine on my machine with both name and location for new projects only

Farvin's machine has the bindings for project names and primary locations for all projects

Please retest

**Comment by rattulator** [comment]
works for your build, will close once farvins lands

**Comment by rattulator** [comment]
It is a thing of beauty Farvin
