### ISSUE TITLE
Dates not formatted correctly

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#26]
Bug ID: 26
Area Path: STAR Project Management
Build Number: 3
Severity: LOW
Priority: LOW
Assigned to: Vijay Brar
Reported By: Shaun Rattue
Reported On: 08/01/16
Reason: Defect
Status: Open
Environment: chrome

When added to the current request, the Date Out / Date In fields are reversed, displaying in YYYY-MM-DD format

**Comment by VijayBrar** [comment]
@fgonsalves Is this something you can sort out? I can't find any date formatting in HTML for table cells but it does seem to be possible in PHP.

**Comment by VijayBrar** [comment]
@rattulator 

This is done and will work fine from @fgonsalves machine.

Please retest when you can.
