### ISSUE TITLE
Layout issues when half-screen

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#27]
Bug ID: 27
Area Path: STAR Project Management
Build Number: 3
Severity: MED
Priority: MED
Assigned to: Vijay Brar
Reported By: Shaun Rattue
Reported On: 08/01/16
Reason: Defect
Status: Open
Environment: chrome

Screen elements do not reformat correctly when screen size is shrunk
![image](https://cloud.githubusercontent.com/assets/15983243/12202423/ae9d2746-b621-11e5-9849-df17b533da9e.png)

**Comment by rattulator** [comment]
This problem is now worse than it was...
![image](https://cloud.githubusercontent.com/assets/15983243/12268858/8b9b182a-b946-11e5-95b9-4c85d822cb1a.png)
The drop downs no longer align when squashed up

**Comment by VijayBrar** [comment]
@rattulator Can you check this out on mine please.

It should be fine now.

**Comment by rattulator** [comment]
This is as bad as it's gonoing to get now it seems
![image](https://cloud.githubusercontent.com/assets/15983243/12354288/d33fa70c-bb8c-11e5-9bbb-2d4c0b50cf9a.png)
