### ISSUE TITLE
Adding a project in IE is formatted wrong

### ISSUE THREAD

**Issue by nikos2015** [VijayBrar/STAR#28]
Adding a project in IE is formatted wrong
Bug ID: 28
Area Path: STAR Project Management
Build Number: 3
Severity: HIGH
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Nikos Sofianos
Reported On: 08/01/16
Reason: Defect
Status: Open
Environment: Internet Explorer

**Comment by rattulator** [comment]
was the resizing / button not working issue.
Closing
