### ISSUE TITLE
Scroll bar appears on the left when nav bar is closed in IE

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#30]
Bug ID: 28
Area Path: STAR Project Management
Build Number: 3
Severity: HIGH
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Nikos Sofianos
Reported On: 08/01/16
Reason: Defect
Status: Open

When the burger button is pressed to minimise the navigation bar on Internet Explorer, a mysterious scroll bar appears
![image](https://cloud.githubusercontent.com/assets/15983243/12202824/a870e84c-b623-11e5-82f3-d69920977dad.png)

**Comment by VijayBrar** [comment]
@rattulator duplicate of #8 

Closing
