### ISSUE TITLE
The box for add additional location is slightly too small on firefox and I.E

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#31]
Bug ID: 31
Area Path: STAR Project Management
Build Number: 3
Severity: Low
Priority: Low
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 11/01/16
Reason: Defect
Status: Open
Environment:  I.E 11.0.9600 , Firefox 43.0.4, not an issue in Chrome 47.0.2526.106
The box for add additional location is slightly too small on firefox and I.E and cuts off part of the text.
![cut off box](https://cloud.githubusercontent.com/assets/15983238/12298148/7d5f5bdc-ba08-11e5-978c-8c85067eab3b.png)

**Comment by VijayBrar** [comment]
@thaffendenplanit 

Fixed. Please retest.
