### ISSUE TITLE
Entry fields not clearing when Add to Request is pressed

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#33]
Bug ID: 33
Area Path: STAR Project Management
Build Number: 3
Severity: Low
Priority: Low
Assigned to: Vijay Brar
Reported By: Shaun Rattue
Reported On: 12/01/16
Reason: Defect
Status: Open
Browser tested: Chrome PC

The drop downs and the date fields dont reset after adding the current selections to the request.

**Comment by VijayBrar** [comment]
@rattulator 

This was removed as it makes the task of adding multiple staff members to the same project rather tedious. All fields reset upon dismissal of the confirmation modal when submission of notifications is complete.
