### ISSUE TITLE
Form not clearing once it's sent

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#34]
Bug ID: 34
Area Path: STAR Project Management
Build Number: 3
Severity: Low
Priority: Low
Assigned to: Vijay Brar
Reported By: Shaun Rattue
Reported On: 12/01/16
Reason: Defect
Status: Open
Tested On: Chrome PC, Android Phone

The form does not reset after pressing Send Notifications.

**Comment by VijayBrar** [comment]
@rattulator 

Fixed. Please retest.
