### ISSUE TITLE
Notification can be sent with no details in the table

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#36]
Bug ID: 36
Area Path: STAR Project Management
Build Number: 3
Severity: High
Priority: High
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 12/01/16
Reason: Defect
Status: Open

Confirmation message is appearing without any details.

**Comment by VijayBrar** [comment]
@thaffendenplanit 

Fixed. Please retest.
