### ISSUE TITLE
Current Request doesn't delete table rows on submitting notification

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#37]
Bug ID: 37
Area Path: STAR Project Management
Build Number: 3
Severity: Med
Priority: Med
Assigned to: Vijay Brar
Reported By: Shaun Rattue
Reported On: 12/01/16
Reason: Defect
Status: Open

Upon pressing Send Notification, the Current Request is cleared of data but the table rows themselves are not deleted. New additions to the request appear below

![image](https://cloud.githubusercontent.com/assets/15983243/12269458/61f66968-b949-11e5-83c4-21e0aad4975f.png)

**Comment by VijayBrar** [comment]
@rattulator 

This shouldn't happen. Where are you seeing this? Browser etc...

**Comment by rattulator** [comment]
seeing in chrome, is still happening. Did it get said somewhere that pressing send notification would redirect to the home screen once it had sent, so the user shouldnt see this anyway?

**Comment by VijayBrar** [comment]
@rattulator Personal details and Travel requests redirect to the Welcome page as per Rachel so that will overcome this. I can force a refresh of the page or more thorough cleansing of the table but for now I think the redirection from the back end will be fine.

**Comment by rattulator** [comment]
Its a backend thing is it? Ill close once farvin finds time for it then

**Comment by VijayBrar** [comment]
@rattulator 

I weaved some magic.

Please retest

**Comment by rattulator** [comment]
i think in  doing so you broke the add to request button

**Comment by rattulator** [comment]
closed
