### ISSUE TITLE
Submit Button on Add New Project ceases to function if window becomes too narrow

### ISSUE THREAD

**Issue by rattulator** [VijayBrar/STAR#38]
Bug ID: 38
Area Path: STAR Project Management
Build Number: 3
Severity: High
Priority: High
Assigned to: Vijay Brar
Reported By: Shaun Rattue
Reported On: 12/01/16
Reason: Defect
Status: Open
Tested on: Chrome PC, Phone and tablet Android 5.02, Iphone, Firefox

When the window is formatted to the constricted mobile layout, with the three Add New buttons stacked vertically instead of horizontally, the Submit button on the Add New Project popup ceases to function

Note: A similar thing happens with the Submit button of Add New Location, but only at even narrower resolutions

12:00
14/01/16

**Comment by VijayBrar** [comment]
@rattulator This should be fixed now.

Please retest.

**Comment by thaffendenplanit** [comment]
This is fixed on your verison but not farvins.

**Comment by rattulator** [comment]
very good
