### ISSUE TITLE
There is no warning message when project address is not entered

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#39]
Bug ID: 39
Area Path: Travel and Accommodation Request
Build Number: 3
Severity: Low
Priority: Low
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 14/01/16
Reason: Defect
Status: Open
Environment: Firefox 43.0.4
There is no warning message when project address is not entered
![no message](https://cloud.githubusercontent.com/assets/15983238/12329927/995ba7a0-bada-11e5-8000-69b3a1783606.png)

**Comment by VijayBrar** [comment]
@thaffendenplanit 

Fixed.
