### ISSUE TITLE
Resizing the home screen window causes the navigation bar to disappear

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#5]
Bug Name: Resizing the home screen window causes the navigation bar to disappear
Bug ID: 05
Area Path: STAR Home screen
Build Number: 1
Severity: HIGH
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 07/12/2015
Reason: Defect
Status: Open
Environment: Firefox verison 42.0, I.E and Chrome

Description:
Resizing the home screen window causes the navigation bar to disappear after clicking the hamburger buttom

Steps To Reproduce:
1) Open STAR home screen
2) Resize screen until hamburger button appears.
3) Click hamburger button
4) Return to full screen
5) Observe hamburger button and navigation bar disappears

**Comment by rattulator** [comment]
Also occurs on Nexus 7 anroid tablet

**Comment by VijayBrar** [comment]
@thaffendenplanit  I've added an override to keep the button on screen at all times. This doesn't stop the sidebar from toggling closed on window resize but does allow the user to reopen it.

@rattulator please retest on your Nexus.
