### ISSUE TITLE
Vaildation message for not enough characters for password only appearing on an empty field

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#6]
Bug Name: Vaildation message for not enough characters for password only appearing on an empty field
Bug ID: 06
Area Path: STAR Login
Build Number: 2
Severity: Medium
Priority: Medium
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 08/12/2015
Reason: Defect
Status: Open
Environment: Firefox verison 42.0, Chrome, I.E

Description:
The vaildation message for not enough characters for password only appears when the password field is totally empty, rather than less than 6 characters.

Steps To Reproduce:
1) Open STAR login page on
2) Click password field
3) Enter 1-5 characters
4) Click Login
5) Observe message does not appear

**Comment by VijayBrar** [comment]
@thaffendenplanit this should be working now
