### ISSUE TITLE
Only chrome is displaying required format for passpord expiry date and date of birth, only chrome has calendar select button

### ISSUE THREAD

**Issue by thaffendenplanit** [VijayBrar/STAR#7]
Bug Name: Only chrome is displaying required format for passpord expiry date and date of birth, only chrome has calendar select button
Bug ID: 07
Area Path: STAR Personal Details
Build Number: 1
Severity: HIGH
Priority: HIGH
Assigned to: Vijay Brar
Reported By: Thomas Haffenden
Reported On: 11

/12/2015
Reason: Defect
Status: Open
Environment: Firefox verison 42.0, I.E

Description:
Only chrome is displaying required format for passpord expiry date and date of birth, only chrome has calendar select button

Steps To Reproduce:
1) Open STAR personal details page on fire of I.E
2) Observe passport expiry and date of birth do not display desired format, also they do not have the option to select date through a calendar.
![chrome being good](https://cloud.githubusercontent.com/assets/15983238/11743355/a8142692-9ffe-11e5-8d8e-0c67f8549fe5.png)
![firefox being bad](https://cloud.githubusercontent.com/assets/15983238/11743425/30e28752-9fff-11e5-8de4-1917b1d178a9.png)

**Comment by VijayBrar** [comment]
@thaffendenplanit date format uniformity is not happening across all browsers right now however a date picker has been added to Firefox and IE.

Please retest.

**Comment by VijayBrar** [comment]
@thaffendenplanit this should now be working
